name: 'Build'
description: 'Sets up the repository'
runs:
  using: 'composite'
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: latest
    - name: Install dependencies
      shell: bash
      run: pnpm install
