name: 'Build'
description: 'Sets up the repository'
runs:
  using: 'composite'
  stes:
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: latest
    - name: Install node.js
      uses: actions/setup-node@v3
    - name: Install dependencies
      shell: bash
      run: pnpm install
