name: Tests
on:
  pull_request:
    branches:
      - main

env:
  VITE_API_URL: http://localhost:3000
  API_SECRET: 84f79269b107d58a9b40bda7ec7af0bf20fab80e323887e4b8219fefc65042d9
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: quotes
  DATABASE_URL: postgres://postgres:postgres@localhost:5432/quotes
  CI: 1

jobs:
  unit-and-integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build
      - name: Run unit tests
        run: pnpm test:backend:unit
      - uses: ./.github/actions/docker-compose
      - name: Run integration tests
        run: pnpm test:backend:int
  e2e-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shard: [1/1, 1/2, 1/3, 1/4]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build
      - uses: ./.github/actions/docker-compose
      - uses: ./.github/actions/playwright
      - uses: ./.github/actions/database
      - name: Run e2e tests
        run: cd ${{ github.workspace }}/e2e && npx playwright test --shard=${{ matrix.shard }}
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: blob-report
          path: ${{ github.workspace }}/e2e/blob-report
          retention-days: 3
