name: Tests
on:
  pull_request:
    branches:
      - main

env:
  VITE_API_URL: ${{ vars.VITE_API_URL }}
  API_SECRET: ${{ secrets.API_SECRET }}
  POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  POSTGRES_DB: ${{ vars.POSTGRES_DB }}
  DATABASE_URL: postgres://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@postgres-service:5432/${{ vars.POSTGRES_DB }}
  CI: 1

jobs:
  unit-and-integration-tests:
    runs-on: ubuntu-latest
    container: node:18

    services:
      postgres-service:
        image: postgres
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ vars.POSTGRES_DB }}
        options: >-
          --health-cmd pg_isready
          --health-interval 1s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        uses: ./.github/actions/prepare

      - name: Run Unit Tests
        run: npx vitest --config ./vitest.config.unit.ts
        working-directory: backend

      - name: Prisma Migrate Deploy
        run: npx prisma migrate deploy

      - name: Run Integration Tests
        run: npx vitest --config ./vitest.config.integration.ts
        working-directory: backend
